### ISSUE TITLE
Remote Studies Platform: track mouse movements, clicks, scrolls

### ISSUE THREAD

**Issue by cooper-mj** [StanfordHCI/HPDS-Online-Platform#10]
Write JavaScript to track movement of the cursor as the individual completes the task. Be sure to track the following:
- Mouse location at each timestep
- Timesteps at which mouse clicks occur
- Timesteps at which scroll events occur

For the purposes of this implementation, since we have yet to determine how the data is to be sent to the backend, it will suffice to print the results of this tracking to the console.

**Comment by emurnane** [comment]
Moving to new repo
