### ISSUE TITLE
Send the recorded video to a server

### ISSUE THREAD

**Issue by jeanmarcel** [StanfordHCI/HPDS-Online-Platform#11]
Currently, it records the video of the user during the task and plays it back using the Javascript library RecordRTC (https://github.com/muaz-khan/WebRTC-Experiment/tree/master/RecordRTC). Now we need to send the recording to a server, which is something that the RecordRTC library has capabilities to do but it has not been implemented yet. 

This might be done using the function invokeSaveAsDialog (https://recordrtc.org/global.html#invokeSaveAsDialog), as mentioned here: https://www.webrtc-experiment.com/RecordRTC/simple-demos/video-recording.html

**Comment by cooper-mj** [comment]
Done. 😊
