### ISSUE TITLE
Remote Studies Platform: ability to adjust screen lighting (brightness, wavelength)

### ISSUE THREAD

**Issue by emurnane** [StanfordHCI/HPDS-Online-Platform#4]
E.g., similar to a program like f.lux https://justgetflux.com/ that changes screen lux and RBG spectrum https://fluxometer.com/rainbow/#!id=Macbook%20Air%202011/6500K-MacbookAir2011

**Comment by cooper-mj** [comment]
@emurnane - is the idea that this would be adjusted on the subject-side or on the researcher-side? And (mostly for my clarity than anything else) what types of experiments might this help to bring onto the platform?

**Comment by emurnane** [comment]
Moving to new repo
