### ISSUE TITLE
Resolve Hosting Options at Stanford

### ISSUE THREAD

**Issue by cooper-mj** [StanfordHCI/HPDS-Online-Platform#9]
Drive clarity on the available server options for hosting at Stanford, since hosting on my personal site, though fun, isn't viable in the long term. To resolve this issue, we will need to:
- Understand the hosting options at Stanford available to us
- Understand basic metrics of each option (e.g. how much traffic can it handle?)
- Understand how to deploy to each option

Then, using this information, make a decision as to which option we use for hosting the platform going forward. This issue will be resolved once the decision has been made.

**Comment by emurnane** [comment]
Currently hosting on Firebase: https://lab-in-a-browser.web.app/
Can shift to a Dartmouth, UDel, or other service if necessary in the future
